#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
WM_PROJECT_DIR=/usr/lib/openfoam/openfoam2212  # Set the WM_PROJECT_DIR
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------
cleanAuxiliary

# Function to delete folders inside the main directory, excluding specified ones
deleteFolders() {
    for dir in */; do
        dirname=$(basename "$dir")
        if [ "$dirname" != "0" ] && [ "$dirname" != "298" ] && [ "$dirname" != "system" ] && [ "$dirname" != "constant" ]; then
            echo "Deleting directory: $dir"
            if rm -rf "$dir"; then
                echo "Directory $dir deleted successfully."
            else
                echo "Failed to delete directory: $dir"
            fi
        fi
    done
}
# Call the function to delete folders
deleteFolders
#------------------------------------------------------------------------------
