#!/bin/sh

WM_PROJECT_DIR=/usr/lib/openfoam/openfoam2212  # Set the WM_PROJECT_DIR

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

# Extract the last part of the current directory as the folder name
foldername=$(basename "$PWD")

# Generate the .foam filename based on the folder name
foamfilename="${foldername}.foam"

# Use the touch command to create the .foam file
touch "$foamfilename"

# runApplication cartesianMesh
runApplication $(getApplication)

#------------------------------------------------------------------------------
